apiVersion: apps/v1
kind: Deployment
metadata:
  name: records-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: records-api
  template:
    metadata:
      labels:
        app: records-api
    spec:
      containers:
      - name: records-api-container
        image: piyush050389/nagp-k8s-assignment:1.2.1
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
            requests:
              memory: 64Mi
              cpu: 128m
            limits:
              memory: 128Mi
              cpu: 256m
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: records-api-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: records-api-config
              key: DB_NAME
        - name: DB_TABLE
          valueFrom:
            configMapKeyRef:
              name: records-api-config
              key: DB_TABLE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: records-api-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: records-api-secret
              key: DB_PASSWORD

